export const data = {
    meals: [
      {
        id: 1,
        name: "Da Alfredo",
        location: "27 Old Gloucester St",
        delivery: true,
        takeaway: true,
        rating: 8,
        price: 3,
        category:"Pizza - Italian",
        recommended:true
      },
      {
        id: 2,
        name: "Burghers",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: false,
        rating: 9,
        price: 2.30,
        toprated:true,
        category:"Burghers",
        recommended:true
      },
      {
        id: 3,
        name: "Vego Life",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: true,
        rating: 6,
        discount: 4,
        price: 2,
        offer: true,
        toprated:true,
        category:"Vegetarian",
        recommended:true
      },
      {
        id: 4,
        name: "Auto Pizza",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: false,
        rating: 7.0,
        price: 5.31,
        category:"Pizza",
        recommended:false
      },
      {
        id: 5,
        name: "Sushi Temple",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: false,
        rating: 6,
        discount: 6,
        price: 3.31,
        offer: true,
        toprated:true,
        category:"Japanese - Sushi",
        recommended:false
      },
      {
        id: 5,
        name: "Alliance",
        location: "27 Old Gloucester St",
        delivery: true,
        takeaway: false,
        rating: 6,
        discount: 20,
        price: 7,
        offer: true,
        toprated:true,
        category:"Chinese",
        recommended:false
      },
      {
        id: 6,
        name: "Dragon Tower",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: true,
        rating: 7.9,
        discount: 7,
        price: 1.11,
        offer: true,
        category:"Sushi",
        recommended:false,
      },
      {
        id: 7,
        name: "El Paso Tacos",
        location: "27 Old Gloucester St",
        delivery: true,
        takeaway: true,
        rating: 8.9,
        price: 1.11,
        category:"Mexican",
        recommended:false
      },
      {
        id: 8,
        name: "Monnalisa",
        location: "27 Old Gloucester St",
        delivery: true,
        takeaway: false,
        rating: 8.9,
        discount: 24,
        price: 9,
        offer: true,
        toprated:true,
        category:"Bakery",
        recommended:true
      },
      {
        id: 9,
        name: "Guachamole",
        location: "135 Newtownards Road",
        delivery: true,
        takeaway: false,
        rating: 9,
        offer: true,
        price: 1.11,
        category:"Mexican",
        recommended:false,
        near:true
      },
      {
        id: 9,
        name: "Pechino Express",
        location: "27 Old Gloucester St",
        delivery: false,
        takeaway: false,
        rating: 7,
        price: 1.11,
        category:"Chinese",
        recommended:false
      }
    ]
}